### PR TITLE
Force crash on NVLink fabric errors instead of silently falling back

### LINKED ISSUE #837: CD kubelet plugin: reliably detect NVLink/fabric error, and crash
May not be the long-term solution but we want NVLink-consuming workload to not be scheduled on such nodes and we want to give operators/users better opportunity to see errors like https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/16a3de4d1b5023106eb664cc790f2d5f4a41031a/cmd/compute-domain-kubelet-plugin/nvlib.go#L207 early on.

Relates to #630 where we expressed

> the no-clique fallback code path may be visited upon unhealthy fabric state with isFabricAttached being false (leading to the CD daemon starting up in noop mode). _This may not be the ideal behavior in the long run._

Crashing the CD plugin container would 
1) start a crash cycle that would automatically pick up when the fabric state gets repaired
2) give opportunity to operators/users to see a problem in the DRA driver's kubelet plugin daemonset (with the CD plugin not reporting readiness).

### PR DESCRIPTION
**Pull request by klueska**
CD kubelet plugin: force crash on NVLink fabric errors instead of silently falling back

Fixes #837

Previously, when NVLink fabric was supported but not attached or had
errors, the plugin would silently fall back to no-clique mode with just
an info log. This made it difficult for operators to detect fabric
problems on systems that should have working MNNVL/IMEX support.

Now the plugin reliably distinguishes between two cases:
1. Platform doesn't support NVLink fabric (pre-Hopper, no NVSwitch)
   → Run in no-clique mode (expected behavior)
2. Platform supports NVLink fabric but it's broken/not attached
   → Crash with clear error message (alerts operators immediately)

This causes the CD plugin container to crash-loop when fabric is broken,
making the problem visible in DaemonSet status and allowing automatic
recovery when fabric is restored.

As part of this, we removed redundant IsFabricAttached() call which was calling
GetGpuFabricInfo() again internally - now we check all conditions
directly using the single info struct we already retrieved.

### CODE REVIEW

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 1]
```diff
@@ -199,26 +199,37 @@ func (l deviceLib) getCliqueID() (string, error) {
...
+			return nil
 		}
-
-		if !isFabricAttached {
-			klog.Infof("no-clique fallback: fabric not attached (device %d/%s)", i, duid)
+		if ret != nvml.SUCCESS {
+			return fmt.Errorf("failed to get GPU fabric info (device %d/%s): %v", i, duid, ret)
+		}
+		if info.State == nvml.GPU_FABRIC_STATE_NOT_SUPPORTED {
+			klog.Infof("no-clique fallback: NVLink fabric not supported (device %d/%s)", i, duid)
```
Comment (elezar) [inline cmd/compute-domain-kubelet-plugin/nvlib.go]: Is this stat the same as the `nvml.ERROR_NOT_SUPPORTED` case above? Should the log message be different?

Comment (klueska) [reply cmd/compute-domain-kubelet-plugin/nvlib.go]: I explicitly wanted the *same* message, but could revisit that decision. The first means that driver doesn't support this call -- the second means that the device itself doesn't support being fabric attached.

Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/nvlib.go]: I appreciate that we may never care about the distinction, but let's still retain the error detail for now.

We can add a suffix like "error: ERROR_NOT_SUPPORTED" or "error: GPU_FABRIC_STATE_NOT_SUPPORTED" in the log message.

Hopefully never needed, but we may appreciate that one day.

To me, this is a classic logging guideline: never swallow error detail unless -- in the most literal sense -- being 100 % sure that it will never create pain down the line. That level of confidence typically only comes after having run the code in the wild for a longer time.

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 2]
```diff
@@ -199,26 +199,37 @@ func (l deviceLib) getCliqueID() (string, error) {
 			return fmt.Errorf("failed to read device uuid (%d): %w", i, ret)
 		}
 
-		isFabricAttached, err := d.IsFabricAttached()
-		if err != nil {
-			return fmt.Errorf("error checking if fabric is attached (device %d/%s): %w", i, duid, err)
+		// Check if platform supports NVLink fabric using GetGpuFabricInfo
+		info, ret := d.GetGpuFabricInfo()
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/nvlib.go:286]: Why not retain the comment that we may want to transition to getting `nvmlGpuFabricInfo_v3_t` which contains more detail?

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 3]
```diff
@@ -199,26 +199,37 @@ func (l deviceLib) getCliqueID() (string, error) {
...
-		// TODO: explore using GetGpuFabricInfoV() which can return
-		// nvmlGpuFabricInfo_v3_t which contains `state`, `status`, and
-		// `healthSummary`. The latter we may at least want to log (may be
-		// "unhealthy"). See
-		// https://docs.nvidia.com/deploy/nvml-api/group__nvmlFabricDefs.html
-		info, ret := d.GetGpuFabricInfo()
-		if ret != nvml.SUCCESS {
-			return fmt.Errorf("failed to get GPU fabric info (device %d/%s): %w", i, duid, ret)
+		// NVLink fabric is supported - check if registration completed
+		if info.State != nvml.GPU_FABRIC_STATE_COMPLETED {
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/nvlib.go:300]: Do all systems that we can be happy on really have `info.State == nvml.GPU_FABRIC_STATE_COMPLETED`? I suppose you got that by carefully reading API docs, yes? :)

File: cmd/compute-domain-kubelet-plugin/nvlib.go
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/nvlib.go:330]: So, when we return this error here -- does it result in a program crash?

Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:330]: Answering my question. Yes, looks like it. We subsequently fail in `NewDeviceState()`:

https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/c06a6cadadb3a786d5e01c4c22d2c4ae9aa75b51/cmd/compute-domain-kubelet-plugin/device_state.go#L103

File: cmd/compute-domain-kubelet-plugin/nvlib.go (hunk 3 above)
Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:300]: I think I ask because so far we did not look at `GPU_FABRIC_STATE_COMPLETED` to identify the happy case; and I wonder if this new condition can break systems that would otherwise be happy with the unpatched code.

I think my question is: are there cases where `info.CliqueId` is populated, NVLink is usable, but `info.State != nvml.GPU_FABRIC_STATE_COMPLETED`? Probably not.

File: cmd/compute-domain-kubelet-plugin/nvlib.go (hunk 2 above)
Comment (klueska) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:286]: comment restored

File: cmd/compute-domain-kubelet-plugin/nvlib.go (hunk 3 above)
Comment (klueska) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:300]: Yes, all systems we want to run on must have `info.State == nvml.GPU_FABRIC_STATE_COMPLETED`. According to the NVML API documentation, the State field indicates the GPU fabric registration state and can be:

* GPU_FABRIC_STATE_NOT_STARTED - Registration not started
* GPU_FABRIC_STATE_IN_PROGRESS - Registration in progress
* GPU_FABRIC_STATE_COMPLETED - Registration completed successfully
* GPU_FABRIC_STATE_NOT_SUPPORTED - Fabric not supported

In the new flow, we only ever check if `info.CliqueId` is only valid when `State == COMPLETED.` Before this PR, we were, indeed, checking CliqueId != 0, but that could theoretically be non-zero even in error states.

The correct approach is to check State == COMPLETED first (which guarantees registration succeeded), then check Status for any errors during registration, and only then trust the CliqueId value.

This change shouldn't break any working systems because if fabric is truly working and usable, the state will be `COMPLETED`. Any other state indicates the fabric isn't fully initialized and we shouldn't proceed.

File: cmd/compute-domain-kubelet-plugin/nvlib.go (hunk 1 above)
Comment (klueska) [reply cmd/compute-domain-kubelet-plugin/nvlib.go]: Updated

File: cmd/compute-domain-kubelet-plugin/nvlib.go (hunk 3 above)
Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:300]: Lovely. I think this was an important exchange for posterity. Thank you for clarifying to precisely.

**Comment by jgehrcke** [comment]
Let's think about how to build a test for this. That strongly relates to https://github.com/NVIDIA/k8s-dra-driver-gpu/issues/648.

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 4]
```diff
@@ -199,25 +199,41 @@ func (l deviceLib) getCliqueID() (string, error) {
...
 		// "unhealthy"). See
 		// https://docs.nvidia.com/deploy/nvml-api/group__nvmlFabricDefs.html
 		info, ret := d.GetGpuFabricInfo()
+		if ret == nvml.ERROR_NOT_SUPPORTED {
+			klog.Infof("no-clique fallback: NVLink fabric not supported by driver (device %d/%s, error: ERROR_NOT_SUPPORTED)", i, duid)
+			return nil
+		}
 		if ret != nvml.SUCCESS {
-			return fmt.Errorf("failed to get GPU fabric info (device %d/%s): %w", i, duid, ret)
+			return fmt.Errorf("failed to get GPU fabric info (device %d/%s): %v", i, duid, ret)
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/nvlib.go:292]: What's the decisive difference here between `v` and `w`? I suppose `w` was pointless because an nvml error isn't a proper go error?

Comment (klueska) [reply cmd/compute-domain-kubelet-plugin/nvlib.go:292]: yeah, `%w` would have printed strangely since ret is not an actual error type. Changing this was mostly a case of -- I'm changing the code around it, so might as well change this too.

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 5]
```diff
@@ -190,6 +191,14 @@ func (l deviceLib) getCliqueID() (string, error) {
 	}
 	defer l.alwaysShutdown()
 
+	if featuregates.Enabled(featuregates.CrashOnNVLinkFabricErrors) {
+		return l.getCliqueIDStrict()
+	}
+	return l.getCliqueIDLegacy()
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/nvlib.go:197]: Naming is hard.

These are good naming choices.

File: cmd/compute-domain-kubelet-plugin/nvlib.go [hunk 6]
```diff
@@ -257,6 +266,91 @@ func (l deviceLib) getCliqueID() (string, error) {
 	return "", fmt.Errorf("unexpected return")
 }
 
+// getCliqueIDStrict performs strict validation of NVLink fabric state and crashes on errors.
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/nvlib.go:269]: > and crashes on errors.

Maybe "is intended to crash the program on errors", but this is really just for posterity (I don't mean to say that we should update this).

File: pkg/featuregates/featuregates.go [hunk 7]
```diff
@@ -47,6 +47,10 @@ const (
 	// ComputeDomainCliques enables using ComputeDomainClique CRD objects instead of
 	// storing daemon info directly in ComputeDomainStatus.Nodes.
 	ComputeDomainCliques featuregate.Feature = "ComputeDomainCliques"
+
+	// CrashOnNVLinkFabricErrors causes the kubelet plugin to crash instead of
```
Comment (jgehrcke) [inline pkg/featuregates/featuregates.go:51]: Maybe "the ComputeDomain kubelet plugin".

But we don't need to do that.
