### PR TITLE
Set proper path for MPS shm dir mount

### LINKED ISSUE #974: Missing support for preVolta MPS?
I'm testing MPS on NVIDIA P4 (`cudaComputeCapability: 6.1.0`, `architecture: Pascal`) and it seems that MPS doesn't work on this GPU (with `hostIPC` and without).
I have no issue testing the same workload on NVIDIA T4.

**Environment**:  GKE cluster
```
kubectl version
Client Version: v1.35.1
Kustomize Version: v5.7.1
Server Version: v1.35.1-gke.1396002
```

**GPU workload** - https://github.com/castai/gpu-demo-app
```
apiVersion: v1
kind: Namespace
metadata:
  name: gpu-demo-mps-pre-volta
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: gpu-demo-app-gpu-mps
  namespace: gpu-demo-mps-pre-volta
spec:
  devices:
    requests:
    - name: mps-gpu
      exactly:
        deviceClassName: gpu.nvidia.com
        selectors:
        - cel:
            expression: |
              device.attributes['gpu.nvidia.com'].productName.lowerAscii().matches('^.*(p4).*$') 
    config:
    - requests: ["mps-gpu"]
      opaque:
        driver: gpu.nvidia.com
        parameters:
          apiVersion: resource.nvidia.com/v1beta1
          kind: GpuConfig
          sharing:
            strategy: MPS
            mpsConfig:
              defaultActiveThreadPercentage: 33
              defaultPinnedDeviceMemoryLimit: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-demo-app-mps
  namespace: gpu-demo-mps-pre-volta
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gpu-demo-app-mps
  template:
    metadata:
      labels:
        app: gpu-demo-app-mps
    spec:
      resourceClaims:
      - name: mps-gpu
        resourceClaimName: gpu-demo-app-gpu-mps
      hostIPC: true
      containers:
      - name: gpu-demo-app
        image: ghcr.io/castai/gpu-demo-app:latest
        ports:
        - containerPort: 5000
        resources:
          claims:
          - name: mps-gpu
            request: mps-gpu
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
```

**ResourceSlice:**
```
kubectl get ResourceSlice gke-kasiak-04-01-cast-pool-6a973d4a-gpu.nvidia.com-r9fdq -o yaml
apiVersion: resource.k8s.io/v1
kind: ResourceSlice
metadata:
  creationTimestamp: "2026-04-01T12:03:45Z"
  generateName: gke-kasiak-04-01-cast-pool-6a973d4a-gpu.nvidia.com-
  generation: 1
  name: gke-kasiak-04-01-cast-pool-6a973d4a-gpu.nvidia.com-r9fdq
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: gke-kasiak-04-01-cast-pool-6a973d4a
    uid: 97da820f-6728-441e-9e7f-fc51fe9cbd24
  resourceVersion: "1775045025309647004"
  uid: fc4fcfab-3cc8-457b-b6ac-79969dc4e987
spec:
  devices:
  - attributes:
      architecture:
        string: Pascal
      brand:
        string: Tesla
      cudaComputeCapability:
        version: 6.1.0
      cudaDriverVersion:
        version: 13.0.0
      driverVersion:
        version: 580.105.8
      productName:
        string: Tesla P4
      resource.kubernetes.io/pciBusID:
        string: "0000:00:04.0"
      resource.kubernetes.io/pcieRoot:
        string: pci0000:00
      type:
        string: gpu
      uuid:
        string: GPU-1b6375ea-bcaf-a28f-288b-dc987ec82fdd
    capacity:
      memory:
        value: 7680Mi
    name: gpu-0
  driver: gpu.nvidia.com
  nodeName: gke-kasiak-04-01-cast-pool-6a973d4a
  pool:
    generation: 1
    name: gke-kasiak-04-01-cast-pool-6a973d4a
    resourceSliceCount: 1
```

**Pods running on the node** - `mps-control-daemon` is running
```
ubectl get pods --all-namespaces -o wide --field-selector spec.nodeName=gke-kasiak-04-01-cast-pool-6a973d4a
NAMESPACE                NAME                                                              READY   STATUS    RESTARTS   AGE   IP             NODE                                  NOMINATED NODE   READINESS GATES
castai-agent             castai-kvisor-agent-xcgwl                                         1/1     Running   0          35m   10.48.135.2    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
gmp-system               collector-t85nd                                                   2/2     Running   0          35m   10.48.135.5    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
gpu-demo-mps-pre-volta   gpu-demo-app-mps-78cdfb44cb-fgskm                                 1/1     Running   0          26m   10.48.135.10   gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
gpu-demo-mps-pre-volta   gpu-demo-app-mps-78cdfb44cb-mjkd5                                 1/1     Running   0          26m   10.48.135.11   gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
gpu-demo-mps-pre-volta   gpu-demo-app-mps-78cdfb44cb-vmksq                                 1/1     Running   0          26m   10.48.135.12   gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
kube-system              fluentbit-gke-pwmrj                                               3/3     Running   0          35m   10.128.0.32    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
kube-system              gke-metrics-agent-lvwff                                           3/3     Running   0          35m   10.128.0.32    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
kube-system              kube-proxy-gke-kasiak-04-01-cast-pool-6a973d4a                    1/1     Running   0          35m   10.128.0.32    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
kube-system              maintenance-handler-cqtrj                                         1/1     Running   0          35m   10.48.135.3    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
kube-system              node-local-dns-g98jt                                              2/2     Running   0          35m   10.128.0.32    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
kube-system              nvidia-driver-installer-847tg                                     1/1     Running   0          35m   10.128.0.32    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
kube-system              pdcsi-node-rrcnj                                                  3/3     Running   0          35m   10.128.0.32    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
nvidia                   mps-control-daemon-963ee7f3-bfdc-4ec4-9e3b-9fd4bd174351-1efzbt2   1/1     Running   0          34m   10.48.135.6    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
nvidia                   nvidia-dra-driver-gpu-kubelet-plugin-fhkhr                        2/2     Running   0          35m   10.48.135.4    gke-kasiak-04-01-cast-pool-6a973d4a   <none>           <none>
```

**Output of `nvidia-smi`:**
```
 # ./nvidia-smi 
Wed Apr  1 12:40:43 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.105.08             Driver Version: 580.105.08     CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla P4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   34C    P8              7W /   75W |     169MiB /   7680MiB |      0%   E. Process |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            7613      C   nvidia-cuda-mps-server                  166MiB |
+-----------------------------------------------------------------------------------------+
```

### PR DESCRIPTION
**Pull request by kasia-kujawa**
Fixes #974 

This unblocks usage of MPS on GPUs which support pre-Volta MPS (e.g. NVIDIA P4) on GKE clusters and it doesn't change default configuration.

The MPS control daemon template hardcoded /driver-root/dev/shm as the container mount path for the MPS  `shm` directory.  This works when the daemon runs inside a chroot (standard NVIDIA DRA driver install, GPU Operator), 
but fails on GKE COS where the daemon runs directly in the container namespace, expecting /dev/shm.        

Change was also tested on NVIDIA T4 which supports Volta MPS.

1.  volumeMounts on EKS, MPS control daemon uses chroot 

```
      volumeMounts:
        - name: driver-root
          mountPath: /driver-root
        - name: mps-shm-directory
          mountPath: /driver-root/dev/shm
        - name: mps-pipe-directory
          mountPath: /driver-root/tmp/nvidia-mps
        - name: mps-log-directory
          mountPath: /driver-root/var/log/nvidia-mps
        - name: kube-api-access-b7kx9
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
```

2. volumeMounts on GKE, MPS control daemon doesn't use chroot 

```
      volumeMounts:
        - name: driver-root
          mountPath: /driver-root
        - name: mps-shm-directory
          mountPath: /dev/shm
        - name: mps-pipe-directory
          mountPath: /driver-root/tmp/nvidia-mps
        - name: mps-log-directory
          mountPath: /driver-root/var/log/nvidia-mps
        - name: kube-api-access-7pbnm
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
          recursiveReadOnly: Disabled
```

### CODE REVIEW

File: cmd/gpu-kubelet-plugin/main.go [hunk 1]
```diff
@@ -159,6 +160,13 @@ func newApp() *cli.App {
 			Destination: &flags.additionalXidsToIgnore,
 			EnvVars:     []string{"ADDITIONAL_XIDS_TO_IGNORE"},
 		},
+		&cli.StringFlag{
```
Comment (visheshtanksale) [inline cmd/gpu-kubelet-plugin/main.go]: if MPS_SHM_MOUNT_PATH="" is set via env var, it renders mountPath:  which is an invalid Kubernetes spec. Need an empty check for this env var

**Comment by kasia-kujawa** [comment]
I have another idea for fixing this issue,  `shm` mount path can be set in this way:

```
func setMpsShmMountPath(hostDriverRoot string) string {
       for _, sh := range []string{"/bin/sh", "/usr/bin/sh"} {
               if _, err := os.Stat(filepath.Join(hostDriverRoot, sh)); err == nil {
                       return filepath.Join(hostDriverRoot, "dev", "shm")
               }
       }
       return "/dev/shm"
}
```

and 


```
func (m *MpsControlDaemon) Start(ctx context.Context, config *configapi.MpsConfi
                MpsLogDirectory:                 m.logDir,
                MpsImageName:                    m.manager.config.flags.imageName,
                FeatureGates:                    featuregates.ToMap(),
-               MpsShmMountPath:                 m.manager.mpsShmMountPath,
+               MpsShmMountPath:                 setMpsShmMountPath(m.manager.hostDriverRoot),
        }


```


This will mirror the logic in the template https://github.com/NVIDIA/k8s-dra-driver-gpu/blob/476b4787f1f75bb4a9c0b8e20604125536514b8c/templates/mps-control-daemon.tmpl.yaml#L32

If you think that it is better idea I can test it tomorrow.

**Comment by shivamerla** [comment]
Yes, validating whether `driverRoot` is actually a proper root filesystem seems like a better approach than introducing yet another Helm variable for this.

**Comment by kasia-kujawa** [comment]
@shivamerla approach was changed and it is ready for review.
I tested this on EKS and GKE.

File: cmd/gpu-kubelet-plugin/sharing_test.go [hunk 2]
```diff
@@ -0,0 +1,78 @@
+/*
+ * Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
```
Comment (shivamerla) [inline cmd/gpu-kubelet-plugin/sharing_test.go]: Please use standard kubernetes headers instead.

File: cmd/gpu-kubelet-plugin/sharing.go [hunk 3]
```diff
@@ -95,6 +103,21 @@ type MpsControlDaemonTemplateData struct {
...
+
+// setMpsShmMountPath returns the container path at which the MPS shm should be mounted in the MPS control daemon pod.
+// It mirrors the approach used by the MPS control daemon template:
+// if a shell exists under /driver-root the daemon runs inside a chroot,
+// so the shm must be visible at /driver-root/dev/shm inside the container,
+// otherwise (e.g. GKE COS) the daemon runs directly in the container namespace and expects /dev/shm.
+func setMpsShmMountPath() string {
+	for _, sh := range mpsChRootShellPaths {
+		if _, err := os.Stat(filepath.Join(driverRootMountDir, sh)); err == nil {
+			return MpsChrootShmMountPath
```
Comment (shivamerla) [inline cmd/gpu-kubelet-plugin/sharing.go]: Ideally this should return a path derived from `driverRootMountDir` rather than a hard-coded constant, so it stays correct if the mount root changes.

File: cmd/gpu-kubelet-plugin/sharing_test.go [hunk 4]
```diff
@@ -0,0 +1,78 @@
...
+	}{
+		"sh at /bin/sh": {
+			setupDriverRoot: func(t *testing.T) string {
+				t.Helper()
+				dir := t.TempDir()
+				require.NoError(t, os.MkdirAll(filepath.Join(dir, "bin"), 0755))
+				require.NoError(t, os.WriteFile(filepath.Join(dir, "bin", "sh"), []byte{}, 0755))
+				return dir
+			},
+			expectedMountPath: MpsChrootShmMountPath,
```
Comment (shivamerla) [inline cmd/gpu-kubelet-plugin/sharing_test.go]: Here the check is performed against the temp directory, but the expected result is a fixed constant and doesn’t reflect that overridden root.

File: cmd/gpu-kubelet-plugin/sharing.go (hunk 3 above)
Comment (kasia-kujawa) [reply cmd/gpu-kubelet-plugin/sharing.go]: do you mean this way `fmt.Sprinf("%s%s", driverRootMountDir,  MpsDefaultShmMountPath)` ?

Comment (shivamerla) [reply cmd/gpu-kubelet-plugin/sharing.go]: or just return `filepath.Join(driverRootMountDir, "dev", "shm")` and with that the check could also be for the existence of that specific device file.

**Review by shivamerla — APPROVED** [review]
LGTM

**Comment by shivamerla** [comment]
@dims please review and provide approval as well.
