### PR TITLE
Clarify locking semantics in CD cleanup and add cleanup mechanism to GPU plugin

### LINKED ISSUE #840: GPU kubelet plugin accumulates stale checkpoint entries indefinitely
The GPU kubelet plugin never cleans up stale checkpoint entries when `Prepare()` fails midway. If a claim preparation is interrupted (e.g., process restart, API server timeout), the claim remains in the checkpoint file in PrepareStarted state forever.

Current behavior:
1. `Prepare()` updates checkpoint to PrepareStarted state
2. `prepareDevices()` fails (e.g., API server error, process crash)
3. Claim remains in checkpoint with PrepareStarted state
4. If `Unprepare()` is called: returns noop without removing from checkpoint
5. Checkpoint entry leaks indefinitely

Impact
* Disk space leak: Checkpoint file grows indefinitely with stale entries
* No cleanup mechanism: Unlike compute-domain plugin, GPU plugin has no periodic cleanup routine
* Inconsistent state: Stale entries remain even after pods/claims are deleted from API server

Context
The compute-domain plugin added checkpoint cleanup in commit f7a3310f (Oct 2025) because it needs to clean up cluster-wide state (node labels, API objects) even for partial preparations. The GPU plugin was deliberately left without this mechanism (commit 614e93d1 comment: "This is currently ignored by the GPU driver").

However, this creates a silent resource leak - while GPU preparations are more node-local, the checkpoint entries themselves still accumulate.

Missing Components
* Compared to compute-domain plugin, GPU plugin is missing:
* `CheckpointCleanupManager`: No periodic cleanup routine
* Name/Namespace fields in checkpoint: Can't efficiently look up claims in API server
* `PrepareStarted` handling in `Unprepare`: Doesn't remove stale entries from checkpoint
* `ResourceClaimToString` helper: Inconsistent logging

### PR DESCRIPTION
**Pull request by klueska**
This PR addresses two checkpoint-related bugs.

Fixes #840

### CODE REVIEW

File: cmd/gpu-kubelet-plugin/cleanup.go [hunk 1]
```diff
@@ -0,0 +1,275 @@
...
+	"k8s.io/apimachinery/pkg/api/errors"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
+	"k8s.io/apimachinery/pkg/types"
+	draclient "k8s.io/dynamic-resource-allocation/client"
+	"k8s.io/dynamic-resource-allocation/kubeletplugin"
+	"k8s.io/klog/v2"
+)
+
+const (
+	ResourceClaimCleanupInterval = 10 * time.Minute
```
Comment (jgehrcke) [inline cmd/gpu-kubelet-plugin/cleanup.go:36]: I'd love to not have code like this duplicated -- but we can address this after merge. Thanks for bringing this to the GPU plugin.

This relates to https://github.com/NVIDIA/k8s-dra-driver-gpu/issues/765.

(edit: this comment applies to the entire file; I mis-placed it)

File: cmd/compute-domain-kubelet-plugin/cleanup.go [hunk 2]
```diff
@@ -97,6 +97,10 @@ func (m *CheckpointCleanupManager) Stop() error {
 // best-effort: errors do not need to be propagated (but are expected to be
 // properly logged).
 func (m *CheckpointCleanupManager) cleanup(ctx context.Context) {
+	// Acquire DeviceState lock to safely read checkpoint (same lock held by Prepare/Unprepare)
+	m.devicestate.Lock()
+	defer m.devicestate.Unlock()
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/cleanup.go]: Could you demonstrate / reproduce a problem that was fixed by adding this lock?

I now revisited the previous thinking, and believe that this is not necessary. Adding some comments below for why I believe so.

File: cmd/compute-domain-kubelet-plugin/cleanup.go [hunk 3]
```diff
@@ -97,6 +97,10 @@ func (m *CheckpointCleanupManager) Stop() error {
...
+
 	cp, err := m.devicestate.getCheckpoint()
 	if err != nil {
 		klog.Errorf("Checkpointed RC cleanup: unable to get checkpoint: %s", err)
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/cleanup.go:114]: Yes, we read not under a lock. 

* For the very unlikely case that we read invalid JSON, we return an error here. The next periodic invocation of the cleanup routine will heal that.
* If we successfully deserialized the JSON into a checkpoint struct: it's useful for subsequent cleanup: all we need to do is to iterate over the claims in PrepareStarted currently known. Any missed claims are covered in the next periodic invocation.

File: cmd/compute-domain-kubelet-plugin/cleanup.go
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/cleanup.go:129]: Now, the mutation is done under the one lock that matters. This `m.unprepareIfStale()` here calls into the proper, outest unprepare function of the driver.

```
	// Pass `nodeUnprepareResource` function in the cleanup manager.
	if err := state.checkpointCleanupManager.Start(ctx, driver.nodeUnprepareResource); err != nil {
		return nil, fmt.Errorf("error starting CheckpointCleanupManager: %w", err)
	}
```

In `driver.nodeUnprepareResource()` we do:

```
release, err := d.pulock.Acquire(ctx, flock.WithTimeout(10*time.Second))
```

**Review by jgehrcke — COMMENTED** [review]
Thanks for putting this together. I believe we need to think this through once again carefully.

I remember that I deliberately didn't want to have one big lock under which this `cleanup()` is performed.

As we iterate over claims-to-be-unprepared, it makes sense to only briefly hold a lock rather locally for every checkpoint mutation. This is done (we perform each attempted mutation under the file-based PU lock).

There is unrelated work we do during `cleanup()` which may take an unpredictable amount of time (API server interaction; which may potentially be slow as we read resource claim detail). I think we should not unnecessarily hold a lock during those times. Otherwise, every cleanup() invocation has the potential to negatively affect the latency of user-triggered prepare()/unprepare() work.

File: cmd/compute-domain-kubelet-plugin/cleanup.go (hunk 2 above)
Comment (klueska) [reply cmd/compute-domain-kubelet-plugin/cleanup.go]: You're right, the lock isn't needed. I'll remove it and add a comment explaining why.

As you point out below, the key insight is that the initial checkpoint read is just discovering candidate claims to check - it doesn't need strong consistency. We then validate each candidate against the API server (the authoritative source of truth for whether a claim is truly stale), and only if the API server confirms it's gone do we call into `nodeUnprepareResource()`, which does the proper read-modify-write under pulock.

So the flow is:
* Optimistic scan (no lock needed): Best-effort read to find PrepareStarted claims. Missing a claim due to concurrent write just means we catch it next iteration.
* Validate: Check API server - this is what determines correctness, not local checkpoint state
* Atomic update (under pulock): Fresh read + write of checkpoint in nodeUnprepareResource()

Holding the `DeviceState` lock during the entire cleanup (which could take seconds with multiple API calls) would unnecessarily block normal `Prepare`/`Unprepare` operations for what is inherently a best-effort periodic cleanup.

Comment (jgehrcke) [reply cmd/compute-domain-kubelet-plugin/cleanup.go]: > So the flow is: [...]

I love these three bullet points, you have explained it better than I did. Yes.

File: cmd/compute-domain-kubelet-plugin/cleanup.go [hunk 4]
```diff
@@ -96,6 +96,18 @@ func (m *CheckpointCleanupManager) Stop() error {
...
+// The lock is not needed because:
+//  1. This initial checkpoint read is just discovering candidate claims to check - it
+//     doesn't need strong consistency. Missing a claim due to concurrent write just
+//     means we catch it on the next periodic iteration.
+//  2. We validate each candidate against the API server (the authoritative source of
+//     truth for whether a claim is truly stale), not the local checkpoint state.
+//  3. The actual checkpoint mutation happens in nodeUnprepareResource(), which properly
+//     acquires the pulock (process-level file lock) for atomic read-modify-write.
+//  4. Holding DeviceState lock during the entire cleanup (which could take seconds with
+//     multiple API calls) would unnecessarily block normal Prepare/Unprepare operations.
```
Comment (jgehrcke) [inline cmd/compute-domain-kubelet-plugin/cleanup.go:110]: 💪 Great! Thank you. With this comment, I feel much better about that, and future maintainers won't... spend too much time :).
