### PR TITLE
Only warn when pcieRoot can't be determined

### LINKED ISSUE #575: GPU kubelet plugin crashes when `pcieRoot` attributes can't be determined
On some VM SKUs (i.e. at least one in Azure), PCI devices are not expressed in the `/sys` filesystem the way that's expected by https://github.com/kubernetes/kubernetes/pull/132296, causing the GPU driver to crash with an error like this:
```
Error: error creating driver: error enumerating all possible devices: error enumerating GPUs and MIG devices: error visiting devices: error visiting device: error getting info for GPU 0: error getting PCIe root for device 0: failed to resolve PCIe Root Complex for PCI Bus ID 0001:00:00.0: symlink target for PCI Bus ID 0001:00:00.0 is invalid: it must start with /sys/devices/pci: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/000000c1-0001-0000-3130-444532304235/pci0001:00/0001:00:00.0
```

Instead of crashing, the driver should be able to continue without setting the device attributes in cases where they aren't needed.

This is where I ran into this specific error:
- Azure's Standard_NC48ads_A100_v4 SKU (2 A100 GPUs)
- Ubuntu 24.04
- Kubernetes v1.34.1
- GPU Operator version: v25.3.3
- NVIDIA DRA driver version: 25.8.0-dev-f2eaddd6

### PR DESCRIPTION
**Pull request by nojnhuh**
This PR makes the GPU/MIG kubelet plugin only log a warning when the standard `pcieRoot` attribute cannot be determined instead of crashing.

Fixes #575

Here's an example of how the new log message looks:

```
W0915 18:12:07.677975       1 nvlib.go:206] error getting PCIe root for device 0, continuing without attribute: failed to resolve PCIe Root Complex for PCI Bus ID 0001:00:00.0: symlink target for PCI Bus ID 0001:00:00.0 is invalid: it must start with /sys/devices/pci: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/ACPI0004:00/VMBUS:00/000000c1-0001-0000-3130-444532304235/pci0001:00/0001:00:00.0
```

### CODE REVIEW

File: cmd/gpu-kubelet-plugin/deviceinfo.go [hunk 1]
```diff
@@ -199,5 +200,8 @@ func (d *MigDeviceInfo) GetDevice() resourceapi.Device {
 			Value: *resource.NewQuantity(1, resource.BinarySI),
 		}
 	}
+	if d.pcieRootAttr.Name != "" {
```
Comment (klueska) [inline cmd/gpu-kubelet-plugin/deviceinfo.go]: Can we make `d.pcieRootAttr` a pointer so we can check `nil` here?

Comment (nojnhuh) [reply cmd/gpu-kubelet-plugin/deviceinfo.go]: Yep, made that change.
